FROM gcc:latest

RUN apt-get update && apt-get install -y \
  build-essential \
  libstdc++6 \
  && rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the source code into the container
COPY . .

# Command to run the application
CMD ["make"]

